# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
jade_version=11.13.2+forge
jei_version=15.20.0.127
geckolib_version=4.7.3
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=essenceofthewild
mod_name=Essence Of The Wild Mod
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=net.mrmisc.essenceofthewild
mod_authors=Zinc Studios, mrMisc29
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.
